// This file is generated by Sapper — do not edit it!
import * as route_0 from "../../../routes/web-push-client.js";
import * as route_1 from "../../../routes/farma/check_ws_consulta_registro_dep_sap_grafico/data.js";
import component_0 from "../../../routes/index.svelte";
import component_1 from "../../../routes/pg-scheduled-tasks/main/index.svelte";
import component_2 from "../../../routes/oms-soporte/index.svelte";
import component_3 from "../../../routes/oms-soporte/control_comunicaciones/index.svelte";
import component_4 from "../../../routes/oms-soporte/fecha_mssql_novedades.svelte";
import component_5 from "../../../routes/oms-soporte/espacio_libre_disco.svelte";
import component_6 from "../../../routes/oms-soporte/jobs_novedades.svelte";
import component_7 from "../../../routes/oms-soporte/lista_precios/farmacia/punto_natural.svelte";
import component_8 from "../../../routes/oms-soporte/lista_precios/farmacia/economicas.svelte";
import component_9 from "../../../routes/oms-soporte/lista_precios/farmacia/medicity.svelte";
import component_10 from "../../../routes/oms-soporte/lista_precios/farmacia/paf.svelte";
import component_11 from "../../../routes/oms-soporte/lista_precios/promo/punto_natural.svelte";
import component_12 from "../../../routes/oms-soporte/lista_precios/promo/economicas.svelte";
import component_13 from "../../../routes/oms-soporte/lista_precios/promo/medicity.svelte";
import component_14 from "../../../routes/oms-soporte/lista_precios/promo/paf.svelte";
import component_15 from "../../../routes/oms-soporte/lista_precios/todas.svelte";
import component_16 from "../../../routes/oms-soporte/control-jobs/resumen/index.svelte";
import component_17 from "../../../routes/oms-soporte/control-jobs/cola/index.svelte";
import component_18 from "../../../routes/oms-soporte/jobs_todos.svelte";
import component_19 from "../../../routes/oms-soporte/farmacias/lista_farmacias.svelte";
import component_20 from "../../../routes/oms-soporte/farmacias/activas_medi.svelte";
import component_21 from "../../../routes/oms-soporte/farmacias/activas_eco.svelte";
import component_22 from "../../../routes/oms-soporte/farmacias/activas_paf.svelte";
import component_23 from "../../../routes/oms-soporte/summary/index.svelte";
import component_24 from "../../../routes/pg-api-web/index.svelte";
import component_25 from "../../../routes/test_pag/index.svelte";
import component_26 from "../../../routes/about.svelte";
import component_27 from "../../../routes/farma/clientes_novedad_con_asignacion_corporativo/index.svelte";
import component_28 from "../../../routes/farma/check_ws_consulta_registro_dep_sap_grafico/index.svelte";
import component_29 from "../../../routes/farma/check_ws_consulta_registro_dep_sap_grafico/test2.svelte";
import component_30 from "../../../routes/farma/check_ws_consulta_registro_dep_sap_grafico/test.svelte";
import component_31 from "../../../routes/farma/ite_integrador_sincronizacion_proveedores/index.svelte";
import component_32 from "../../../routes/farma/ite_integradorsap_tbl_cliente_duplicados/index.svelte";
import component_33 from "../../../routes/farma/cargar_ventas_matriz_faltante_sap/index.svelte";
import component_34 from "../../../routes/farma/log_pa_cambiar_estado_factReserv/index.svelte";
import component_35 from "../../../routes/farma/carga_transferencias_farmacias/index.svelte";
import component_36 from "../../../routes/farma/carga_devoluciones_farmacias/index.svelte";
import component_37 from "../../../routes/farma/consulta_guias_con_novedades/index.svelte";
import component_38 from "../../../routes/farma/fact_elect_pv_car_sin_aut/index.svelte";
import component_39 from "../../../routes/farma/fact_elect_sap_novedades/index.svelte";
import component_40 from "../../../routes/farma/carga_ventas_matriz_sap/index.svelte";
import component_41 from "../../../routes/farma/control_comunicaciones/index.svelte";
import component_42 from "../../../routes/farma/carga_planes_mercadeo/index.svelte";
import component_43 from "../../../routes/farma/fact_elect_pv_sin_aut/index.svelte";
import component_44 from "../../../routes/farma/log_seguimiento_sap/index.svelte";
import component_45 from "../../../routes/farma/registro_depositos/consultar.svelte";
import component_46 from "../../../routes/farma/inconsistencias/revision/index.svelte";
import component_47 from "../../../routes/farma/inconsistencias/revision/consultar.svelte";
import component_48 from "../../../routes/farma/fact_elect_sap/index.svelte";
import component_49 from "../../../routes/farma/farmacias/index.svelte";
import component_50 from "../../../routes/oms/index.svelte";
import component_51 from "../../../routes/oms/summary/index.svelte";
import root from "./layout.svelte";
import error from "../../../routes/_error.svelte";

const d = decodeURIComponent;

export const manifest = {
	server_routes: [
		{
			// web-push-client.js
			pattern: /^\/web-push-client\/?$/,
			handlers: route_0,
			params: () => ({})
		},

		{
			// farma/check_ws_consulta_registro_dep_sap_grafico/data.js
			pattern: /^\/farma\/check_ws_consulta_registro_dep_sap_grafico\/data\/?$/,
			handlers: route_1,
			params: () => ({})
		}
	],

	pages: [
		{
			// index.svelte
			pattern: /^\/$/,
			parts: [
				{ name: "index", file: "index.svelte", component: component_0 }
			]
		},

		{
			// pg-scheduled-tasks/main/index.svelte
			pattern: /^\/pg-scheduled-tasks\/main\/?$/,
			parts: [
				null,
				{ name: "pg$45scheduled$45tasks_main", file: "pg-scheduled-tasks/main/index.svelte", component: component_1 }
			]
		},

		{
			// oms-soporte/index.svelte
			pattern: /^\/oms-soporte\/?$/,
			parts: [
				{ name: "oms$45soporte", file: "oms-soporte/index.svelte", component: component_2 }
			]
		},

		{
			// oms-soporte/control_comunicaciones/index.svelte
			pattern: /^\/oms-soporte\/control_comunicaciones\/?$/,
			parts: [
				null,
				{ name: "oms$45soporte_control_comunicaciones", file: "oms-soporte/control_comunicaciones/index.svelte", component: component_3 }
			]
		},

		{
			// oms-soporte/fecha_mssql_novedades.svelte
			pattern: /^\/oms-soporte\/fecha_mssql_novedades\/?$/,
			parts: [
				null,
				{ name: "oms$45soporte_fecha_mssql_novedades", file: "oms-soporte/fecha_mssql_novedades.svelte", component: component_4 }
			]
		},

		{
			// oms-soporte/espacio_libre_disco.svelte
			pattern: /^\/oms-soporte\/espacio_libre_disco\/?$/,
			parts: [
				null,
				{ name: "oms$45soporte_espacio_libre_disco", file: "oms-soporte/espacio_libre_disco.svelte", component: component_5 }
			]
		},

		{
			// oms-soporte/jobs_novedades.svelte
			pattern: /^\/oms-soporte\/jobs_novedades\/?$/,
			parts: [
				null,
				{ name: "oms$45soporte_jobs_novedades", file: "oms-soporte/jobs_novedades.svelte", component: component_6 }
			]
		},

		{
			// oms-soporte/lista_precios/farmacia/punto_natural.svelte
			pattern: /^\/oms-soporte\/lista_precios\/farmacia\/punto_natural\/?$/,
			parts: [
				null,
				null,
				null,
				{ name: "oms$45soporte_lista_precios_farmacia_punto_natural", file: "oms-soporte/lista_precios/farmacia/punto_natural.svelte", component: component_7 }
			]
		},

		{
			// oms-soporte/lista_precios/farmacia/economicas.svelte
			pattern: /^\/oms-soporte\/lista_precios\/farmacia\/economicas\/?$/,
			parts: [
				null,
				null,
				null,
				{ name: "oms$45soporte_lista_precios_farmacia_economicas", file: "oms-soporte/lista_precios/farmacia/economicas.svelte", component: component_8 }
			]
		},

		{
			// oms-soporte/lista_precios/farmacia/medicity.svelte
			pattern: /^\/oms-soporte\/lista_precios\/farmacia\/medicity\/?$/,
			parts: [
				null,
				null,
				null,
				{ name: "oms$45soporte_lista_precios_farmacia_medicity", file: "oms-soporte/lista_precios/farmacia/medicity.svelte", component: component_9 }
			]
		},

		{
			// oms-soporte/lista_precios/farmacia/paf.svelte
			pattern: /^\/oms-soporte\/lista_precios\/farmacia\/paf\/?$/,
			parts: [
				null,
				null,
				null,
				{ name: "oms$45soporte_lista_precios_farmacia_paf", file: "oms-soporte/lista_precios/farmacia/paf.svelte", component: component_10 }
			]
		},

		{
			// oms-soporte/lista_precios/promo/punto_natural.svelte
			pattern: /^\/oms-soporte\/lista_precios\/promo\/punto_natural\/?$/,
			parts: [
				null,
				null,
				null,
				{ name: "oms$45soporte_lista_precios_promo_punto_natural", file: "oms-soporte/lista_precios/promo/punto_natural.svelte", component: component_11 }
			]
		},

		{
			// oms-soporte/lista_precios/promo/economicas.svelte
			pattern: /^\/oms-soporte\/lista_precios\/promo\/economicas\/?$/,
			parts: [
				null,
				null,
				null,
				{ name: "oms$45soporte_lista_precios_promo_economicas", file: "oms-soporte/lista_precios/promo/economicas.svelte", component: component_12 }
			]
		},

		{
			// oms-soporte/lista_precios/promo/medicity.svelte
			pattern: /^\/oms-soporte\/lista_precios\/promo\/medicity\/?$/,
			parts: [
				null,
				null,
				null,
				{ name: "oms$45soporte_lista_precios_promo_medicity", file: "oms-soporte/lista_precios/promo/medicity.svelte", component: component_13 }
			]
		},

		{
			// oms-soporte/lista_precios/promo/paf.svelte
			pattern: /^\/oms-soporte\/lista_precios\/promo\/paf\/?$/,
			parts: [
				null,
				null,
				null,
				{ name: "oms$45soporte_lista_precios_promo_paf", file: "oms-soporte/lista_precios/promo/paf.svelte", component: component_14 }
			]
		},

		{
			// oms-soporte/lista_precios/todas.svelte
			pattern: /^\/oms-soporte\/lista_precios\/todas\/?$/,
			parts: [
				null,
				null,
				{ name: "oms$45soporte_lista_precios_todas", file: "oms-soporte/lista_precios/todas.svelte", component: component_15 }
			]
		},

		{
			// oms-soporte/control-jobs/resumen/index.svelte
			pattern: /^\/oms-soporte\/control-jobs\/resumen\/?$/,
			parts: [
				null,
				null,
				{ name: "oms$45soporte_control$45jobs_resumen", file: "oms-soporte/control-jobs/resumen/index.svelte", component: component_16 }
			]
		},

		{
			// oms-soporte/control-jobs/cola/index.svelte
			pattern: /^\/oms-soporte\/control-jobs\/cola\/?$/,
			parts: [
				null,
				null,
				{ name: "oms$45soporte_control$45jobs_cola", file: "oms-soporte/control-jobs/cola/index.svelte", component: component_17 }
			]
		},

		{
			// oms-soporte/jobs_todos.svelte
			pattern: /^\/oms-soporte\/jobs_todos\/?$/,
			parts: [
				null,
				{ name: "oms$45soporte_jobs_todos", file: "oms-soporte/jobs_todos.svelte", component: component_18 }
			]
		},

		{
			// oms-soporte/farmacias/lista_farmacias.svelte
			pattern: /^\/oms-soporte\/farmacias\/lista_farmacias\/?$/,
			parts: [
				null,
				null,
				{ name: "oms$45soporte_farmacias_lista_farmacias", file: "oms-soporte/farmacias/lista_farmacias.svelte", component: component_19 }
			]
		},

		{
			// oms-soporte/farmacias/activas_medi.svelte
			pattern: /^\/oms-soporte\/farmacias\/activas_medi\/?$/,
			parts: [
				null,
				null,
				{ name: "oms$45soporte_farmacias_activas_medi", file: "oms-soporte/farmacias/activas_medi.svelte", component: component_20 }
			]
		},

		{
			// oms-soporte/farmacias/activas_eco.svelte
			pattern: /^\/oms-soporte\/farmacias\/activas_eco\/?$/,
			parts: [
				null,
				null,
				{ name: "oms$45soporte_farmacias_activas_eco", file: "oms-soporte/farmacias/activas_eco.svelte", component: component_21 }
			]
		},

		{
			// oms-soporte/farmacias/activas_paf.svelte
			pattern: /^\/oms-soporte\/farmacias\/activas_paf\/?$/,
			parts: [
				null,
				null,
				{ name: "oms$45soporte_farmacias_activas_paf", file: "oms-soporte/farmacias/activas_paf.svelte", component: component_22 }
			]
		},

		{
			// oms-soporte/summary/index.svelte
			pattern: /^\/oms-soporte\/summary\/?$/,
			parts: [
				null,
				{ name: "oms$45soporte_summary", file: "oms-soporte/summary/index.svelte", component: component_23 }
			]
		},

		{
			// pg-api-web/index.svelte
			pattern: /^\/pg-api-web\/?$/,
			parts: [
				{ name: "pg$45api$45web", file: "pg-api-web/index.svelte", component: component_24 }
			]
		},

		{
			// test_pag/index.svelte
			pattern: /^\/test_pag\/?$/,
			parts: [
				{ name: "test_pag", file: "test_pag/index.svelte", component: component_25 }
			]
		},

		{
			// about.svelte
			pattern: /^\/about\/?$/,
			parts: [
				{ name: "about", file: "about.svelte", component: component_26 }
			]
		},

		{
			// farma/clientes_novedad_con_asignacion_corporativo/index.svelte
			pattern: /^\/farma\/clientes_novedad_con_asignacion_corporativo\/?$/,
			parts: [
				null,
				{ name: "farma_clientes_novedad_con_asignacion_corporativo", file: "farma/clientes_novedad_con_asignacion_corporativo/index.svelte", component: component_27 }
			]
		},

		{
			// farma/check_ws_consulta_registro_dep_sap_grafico/index.svelte
			pattern: /^\/farma\/check_ws_consulta_registro_dep_sap_grafico\/?$/,
			parts: [
				null,
				{ name: "farma_check_ws_consulta_registro_dep_sap_grafico", file: "farma/check_ws_consulta_registro_dep_sap_grafico/index.svelte", component: component_28 }
			]
		},

		{
			// farma/check_ws_consulta_registro_dep_sap_grafico/test2.svelte
			pattern: /^\/farma\/check_ws_consulta_registro_dep_sap_grafico\/test2\/?$/,
			parts: [
				null,
				null,
				{ name: "farma_check_ws_consulta_registro_dep_sap_grafico_test2", file: "farma/check_ws_consulta_registro_dep_sap_grafico/test2.svelte", component: component_29 }
			]
		},

		{
			// farma/check_ws_consulta_registro_dep_sap_grafico/test.svelte
			pattern: /^\/farma\/check_ws_consulta_registro_dep_sap_grafico\/test\/?$/,
			parts: [
				null,
				null,
				{ name: "farma_check_ws_consulta_registro_dep_sap_grafico_test", file: "farma/check_ws_consulta_registro_dep_sap_grafico/test.svelte", component: component_30 }
			]
		},

		{
			// farma/ite_integrador_sincronizacion_proveedores/index.svelte
			pattern: /^\/farma\/ite_integrador_sincronizacion_proveedores\/?$/,
			parts: [
				null,
				{ name: "farma_ite_integrador_sincronizacion_proveedores", file: "farma/ite_integrador_sincronizacion_proveedores/index.svelte", component: component_31 }
			]
		},

		{
			// farma/ite_integradorsap_tbl_cliente_duplicados/index.svelte
			pattern: /^\/farma\/ite_integradorsap_tbl_cliente_duplicados\/?$/,
			parts: [
				null,
				{ name: "farma_ite_integradorsap_tbl_cliente_duplicados", file: "farma/ite_integradorsap_tbl_cliente_duplicados/index.svelte", component: component_32 }
			]
		},

		{
			// farma/cargar_ventas_matriz_faltante_sap/index.svelte
			pattern: /^\/farma\/cargar_ventas_matriz_faltante_sap\/?$/,
			parts: [
				null,
				{ name: "farma_cargar_ventas_matriz_faltante_sap", file: "farma/cargar_ventas_matriz_faltante_sap/index.svelte", component: component_33 }
			]
		},

		{
			// farma/log_pa_cambiar_estado_factReserv/index.svelte
			pattern: /^\/farma\/log_pa_cambiar_estado_factReserv\/?$/,
			parts: [
				null,
				{ name: "farma_log_pa_cambiar_estado_factReserv", file: "farma/log_pa_cambiar_estado_factReserv/index.svelte", component: component_34 }
			]
		},

		{
			// farma/carga_transferencias_farmacias/index.svelte
			pattern: /^\/farma\/carga_transferencias_farmacias\/?$/,
			parts: [
				null,
				{ name: "farma_carga_transferencias_farmacias", file: "farma/carga_transferencias_farmacias/index.svelte", component: component_35 }
			]
		},

		{
			// farma/carga_devoluciones_farmacias/index.svelte
			pattern: /^\/farma\/carga_devoluciones_farmacias\/?$/,
			parts: [
				null,
				{ name: "farma_carga_devoluciones_farmacias", file: "farma/carga_devoluciones_farmacias/index.svelte", component: component_36 }
			]
		},

		{
			// farma/consulta_guias_con_novedades/index.svelte
			pattern: /^\/farma\/consulta_guias_con_novedades\/?$/,
			parts: [
				null,
				{ name: "farma_consulta_guias_con_novedades", file: "farma/consulta_guias_con_novedades/index.svelte", component: component_37 }
			]
		},

		{
			// farma/fact_elect_pv_car_sin_aut/index.svelte
			pattern: /^\/farma\/fact_elect_pv_car_sin_aut\/?$/,
			parts: [
				null,
				{ name: "farma_fact_elect_pv_car_sin_aut", file: "farma/fact_elect_pv_car_sin_aut/index.svelte", component: component_38 }
			]
		},

		{
			// farma/fact_elect_sap_novedades/index.svelte
			pattern: /^\/farma\/fact_elect_sap_novedades\/?$/,
			parts: [
				null,
				{ name: "farma_fact_elect_sap_novedades", file: "farma/fact_elect_sap_novedades/index.svelte", component: component_39 }
			]
		},

		{
			// farma/carga_ventas_matriz_sap/index.svelte
			pattern: /^\/farma\/carga_ventas_matriz_sap\/?$/,
			parts: [
				null,
				{ name: "farma_carga_ventas_matriz_sap", file: "farma/carga_ventas_matriz_sap/index.svelte", component: component_40 }
			]
		},

		{
			// farma/control_comunicaciones/index.svelte
			pattern: /^\/farma\/control_comunicaciones\/?$/,
			parts: [
				null,
				{ name: "farma_control_comunicaciones", file: "farma/control_comunicaciones/index.svelte", component: component_41 }
			]
		},

		{
			// farma/carga_planes_mercadeo/index.svelte
			pattern: /^\/farma\/carga_planes_mercadeo\/?$/,
			parts: [
				null,
				{ name: "farma_carga_planes_mercadeo", file: "farma/carga_planes_mercadeo/index.svelte", component: component_42 }
			]
		},

		{
			// farma/fact_elect_pv_sin_aut/index.svelte
			pattern: /^\/farma\/fact_elect_pv_sin_aut\/?$/,
			parts: [
				null,
				{ name: "farma_fact_elect_pv_sin_aut", file: "farma/fact_elect_pv_sin_aut/index.svelte", component: component_43 }
			]
		},

		{
			// farma/log_seguimiento_sap/index.svelte
			pattern: /^\/farma\/log_seguimiento_sap\/?$/,
			parts: [
				null,
				{ name: "farma_log_seguimiento_sap", file: "farma/log_seguimiento_sap/index.svelte", component: component_44 }
			]
		},

		{
			// farma/registro_depositos/consultar.svelte
			pattern: /^\/farma\/registro_depositos\/consultar\/?$/,
			parts: [
				null,
				null,
				{ name: "farma_registro_depositos_consultar", file: "farma/registro_depositos/consultar.svelte", component: component_45 }
			]
		},

		{
			// farma/inconsistencias/revision/index.svelte
			pattern: /^\/farma\/inconsistencias\/revision\/?$/,
			parts: [
				null,
				null,
				{ name: "farma_inconsistencias_revision", file: "farma/inconsistencias/revision/index.svelte", component: component_46 }
			]
		},

		{
			// farma/inconsistencias/revision/consultar.svelte
			pattern: /^\/farma\/inconsistencias\/revision\/consultar\/?$/,
			parts: [
				null,
				null,
				null,
				{ name: "farma_inconsistencias_revision_consultar", file: "farma/inconsistencias/revision/consultar.svelte", component: component_47 }
			]
		},

		{
			// farma/fact_elect_sap/index.svelte
			pattern: /^\/farma\/fact_elect_sap\/?$/,
			parts: [
				null,
				{ name: "farma_fact_elect_sap", file: "farma/fact_elect_sap/index.svelte", component: component_48 }
			]
		},

		{
			// farma/farmacias/index.svelte
			pattern: /^\/farma\/farmacias\/?$/,
			parts: [
				null,
				{ name: "farma_farmacias", file: "farma/farmacias/index.svelte", component: component_49 }
			]
		},

		{
			// oms/index.svelte
			pattern: /^\/oms\/?$/,
			parts: [
				{ name: "oms", file: "oms/index.svelte", component: component_50 }
			]
		},

		{
			// oms/summary/index.svelte
			pattern: /^\/oms\/summary\/?$/,
			parts: [
				null,
				{ name: "oms_summary", file: "oms/summary/index.svelte", component: component_51 }
			]
		}
	],

	root,
	root_preload: () => {},
	error
};

export const build_dir = "__sapper__/dev";

export const src_dir = "src";

export const dev = true;